//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Appraisal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EA_Instruction
    {
        public string Ins_ID { get; set; }
        public string Main_Title { get; set; }
        public string Yellow_Title { get; set; }
        public string Y_1 { get; set; }
        public string Y_2 { get; set; }
        public string Y_3 { get; set; }
        public string Blue_Title { get; set; }
        public string B_1 { get; set; }
        public string Green_Title { get; set; }
        public string G_1 { get; set; }
        public string G_2 { get; set; }
        public string G_3 { get; set; }
        public string G_4 { get; set; }
        public string G_5 { get; set; }
        public string G_6 { get; set; }
        public string G_7 { get; set; }
    }
}
