//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Appraisal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EA_Leave
    {
        public long EA_Leav { get; set; }
        public string Emp_no { get; set; }
        public string ABSs { get; set; }
        public string Casual { get; set; }
        public string EL { get; set; }
        public string EUPL { get; set; }
        public string HL { get; set; }
        public string ML { get; set; }
        public string RL { get; set; }
        public string UPL { get; set; }
        public string Late_Min { get; set; }
        public string Late_Time { get; set; }
        public string Years { get; set; }
        public string Users_ID { get; set; }
    }
}
