//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Appraisal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EDIEntities : DbContext
    {
        public EDIEntities()
            : base("name=EDIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EA_Instruction> EA_Instruction { get; set; }
        public virtual DbSet<EA_Leave> EA_Leave { get; set; }
        public virtual DbSet<EA_Position> EA_Position { get; set; }
        public virtual DbSet<EA_Section_1> EA_Section_1 { get; set; }
        public virtual DbSet<EA_Section_2> EA_Section_2 { get; set; }
        public virtual DbSet<EA_Section_3> EA_Section_3 { get; set; }
        public virtual DbSet<EA_Section_4> EA_Section_4 { get; set; }
        public virtual DbSet<EA_Section_5> EA_Section_5 { get; set; }
        public virtual DbSet<EA_Section_6> EA_Section_6 { get; set; }
        public virtual DbSet<EA_Users> EA_Users { get; set; }
    }
}
