//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Appraisal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EA_Section_5
    {
        public int Sec5_ID { get; set; }
        public string Emp_ID { get; set; }
        public string Man_ID { get; set; }
        public string Area { get; set; }
        public string Outcome { get; set; }
        public string Desire { get; set; }
        public string Terms { get; set; }
        public string Years { get; set; }
    
        public virtual EA_Users EA_Users { get; set; }
    }
}
