//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Appraisal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EA_Section_4
    {
        public int Sec4_ID { get; set; }
        public string Emp_ID { get; set; }
        public string Man_ID { get; set; }
        public string Objective_sec4 { get; set; }
        public string Standards_sec4 { get; set; }
        public string Measure_sec4 { get; set; }
        public string Years { get; set; }
    
        public virtual EA_Users EA_Users { get; set; }
    }
}
