//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Appraisal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EA_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EA_Users()
        {
            this.EA_Section_1 = new HashSet<EA_Section_1>();
            this.EA_Section_2 = new HashSet<EA_Section_2>();
            this.EA_Section_3 = new HashSet<EA_Section_3>();
            this.EA_Section_4 = new HashSet<EA_Section_4>();
            this.EA_Section_5 = new HashSet<EA_Section_5>();
            this.EA_Section_6 = new HashSet<EA_Section_6>();
        }
    
        public string Users_ID { get; set; }
        public string Users_Code { get; set; }
        public string Users_Fname { get; set; }
        public string Users_Email { get; set; }
        public string Users_Position { get; set; }
        public string Manager_ID { get; set; }
        public string Username { get; set; }
        public string Passkey { get; set; }
        public string Department_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EA_Section_1> EA_Section_1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EA_Section_2> EA_Section_2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EA_Section_3> EA_Section_3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EA_Section_4> EA_Section_4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EA_Section_5> EA_Section_5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EA_Section_6> EA_Section_6 { get; set; }
    }
}
