//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Appraisal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ruby_Emp
    {
        public long Emp_id { get; set; }
        public string Emp_Code { get; set; }
        public string Emp_Name { get; set; }
        public Nullable<int> Department { get; set; }
        public string Passkey { get; set; }
        public string Barkey { get; set; }
        public string Emp_Photo { get; set; }
        public byte Printed { get; set; }
        public byte FolkLift { get; set; }
        public string Rights { get; set; }
        public byte Admin { get; set; }
        public Nullable<byte> Skill_Level { get; set; }
    }
}
